// React/Day02/src/components/ProductForm.jsx
import { useState } from "react"

export function ProductForm( props ) {


    let { onAddProduct } = props

    let [ formValues, setFormValues ] = useState( {
        name: '',
        price: '',
        isShippingFree: false
    } )

    let getInputValue = ( e ) => {

        setFormValues( {
            ...formValues,
            [ e.target.name ]: e.target.name == 'isShippingFree' ? e.target.checked : e.target.value
        } )


    }

    let productHandler = ( e ) => {
        e.preventDefault()
        onAddProduct( formValues )
        setFormValues( {
            name: '',
            price: '',
            isShippingFree: false
        } )

    }
    return (
        <div className="container p-4">

            <h1 className="text-center">Add New Product</h1>

            <form className="mt-4" onSubmit={productHandler}>
                <input onChange={getInputValue} type="text" name='name' value={formValues.name} placeholder="Enter Product Name" className="form-control mb-3" />
                <input onChange={getInputValue} type="number" value={formValues.price} name='price' placeholder="Enter Product Price" className="form-control mb-3" />
                <input onChange={getInputValue} type="checkbox" checked={formValues.isShippingFree} name='isShippingFree' placeholder="Enter Product Price" className="mb-3" /> freeShipping
                <button className="d-block btn btn-dark mt-3" type="submit">Add New Product</button>
            </form>
        </div>
    )
}

// Angular/Day05/src/app/components/products/product-form/product-form.component.ts
import { Component } from '@angular/core';
import { StaticProductService } from '../../../services/static-product.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-product-form',
  imports: [],
  templateUrl: './product-form.component.html',
  styleUrl: './product-form.component.css',
})
export class ProductFormComponent {
  constructor(
    private productService: StaticProductService,
    private router: Router
  ) {}
  productHandler() {
    this.productService.addNewProduct({
      id: 1,
      name: 'New Product',
      price: 300,
      quantity: 10,
    });
    this.router.navigate(['/products']);
  }
}

<div class="container mt-4">
  <form (submit)="productHandler()">
    <div class="mb-3">
      <label for="productNameInput" class="form-label">Product Name</label>
      <input
        type="text"
        name="productName"
        class="form-control"
        id="productNameInput"
        aria-describedby="emailHelp"
        placeholder="Enter PRoduct Name"
      />
    </div>
    <div class="mb-3">
      <label for="productPriceInput" class="form-label">Product Price</label>
      <input
        type="number"
        name="productPrice"
        class="form-control"
        id="productPriceInput"
        aria-describedby="emailHelp"
        placeholder="Enter Product Price"
      />
    </div>
    <div class="mb-3">
      <label for="productPriceInput" class="form-label">Product Quantity</label>
      <input
        type="number"
        name="productQuantity"
        class="form-control"
        id="productQuantityInput"
        aria-describedby="emailHelp"
        placeholder="Enter Product Quantity"
      />
    </div>

    <button type="submit" class="btn btn-dark">add New PRoduct</button>
  </form>
</div>
